POST https://8080-christhirst-oauth-k190qu9sfa8.ws-eu45.gitpod.io/token HTTP/1.1
    Host: 8080-christhirst-oauth-k190qu9sfa8.ws-eu45.gitpod.io 
    Content-Type: application/x-www-form-urlencoded
  
    &client_id=s6BhdRkqt3
    &client_secret=some_secret12345
    &grant_type=refresh_token
    &refresh_token=8xLOxBtZp8
    &scope=openid%20profile