POST https://8080-christhirst-oauth-k190qu9sfa8.ws-eu45.gitpod.io/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Fiddler
Host: 8080-christhirst-oauth-k190qu9sfa8.ws-eu45.gitpod.io
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
  &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb

POST /token HTTP/1.1
  Host: server.example.com
  Content-Type: application/x-www-form-urlencoded

    &client_id=s6BhdRkqt3
    &nonce=testnonce
    &client_secret=some_secret12345
    &grant_type=refresh_token
    &refresh_token=8xLOxBtZp8
    &scope=openid%20profile