POST https://8080-christhirst-oauth-k190qu9sfa8.ws-eu46.gitpod.io/userinfo HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Fiddler
Host: 8080-christhirst-oauth-k190qu9sfa8.ws-eu46.gitpod.io
Authorization: Basic QWFsaXlhaDoxMjM0NQ==

grant_type=password&username=Aaliyah&password=12345&scope=openid



